# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude_types:
          - image
      - id: fix-encoding-pragma
        args: [ --remove ]
      - id: mixed-line-ending
        args: [ --fix=lf ]
        exclude_types:
          - batch
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: e83a1a42a73284d301c05baaffc176042ffbcf82
    hooks:
      - id: sphinx-lint
  - repo: local
    hooks:
      - id: unasync
        name: unasync
        entry: bin/make-unasync
        language: system
        files: "^(neo4j/_async|tests/(unit|integration)/async_|testkitbackend/_async)/.*"
      - id: mypy
        name: mypy static type check
        entry: mypy
        args: [ --show-error-codes, neo4j, tests, testkitbackend ]
        'types_or': [ python, pyi ]
        language: system
        pass_filenames: false
        require_serial: true
