[package]
name = "neo4j-rust-ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "neo4j_rust_ext"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
